version: '3.8'
services:
  gateway:
    build:
      context:  gateway/
      dockerfile: Dockerfile
    image: shareit-gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build:
      context: server/
      dockerfile: Dockerfile
    image: shareit-server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - POSTGRES_DATASOURCE_USERNAME=postgres
      - POSTGRES_DATASOURCE_PASSWORD=nastya1029384756
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver

  db:
    image: postgres:13.7-alpine
    container_name: shareit-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nastya1029384756